### ISSUE TITLE
Link to Google Doc with Codepen examples

### ISSUE THREAD

**Issue by NoahTheDuke** [lyonsbp/vuetiful-lyrics#1]
I attended your panel on Saturday (Penguicon 2019) and loved it but seem to have lost the link to the Google doc you directed us to that had the CodePen "in between stages". I feel like it would be helpful to have access to that in this repo!

Thanks so much for giving that talk, it was immensely helpful.

**Comment by lyonsbp** [comment]
Hey thanks a bunch for the comment! Here is the link to the Google doc, and I will add it to the readme as well.
